### ISSUE TITLE
Command Interface

### ISSUE THREAD

**Issue by nat2001** [peterkvt80/vbit2#20]
When I try to select a page with P, vbit crashes and I get a segmentation fault

**Comment by nat2001** [comment]
never mind i was doing it wrong

**Comment by ZXGuesser** [comment]
Not particularly surprising as that code isn't finished which is why I rolled the master branch back to where everything else was stable. Are you using the newfor branch?

**Comment by nat2001** [comment]
No, I'm using the master branch all right. I just didn't realise the <> were part of the command like a goat
