### ISSUE TITLE
Using my own page server

### ISSUE THREAD

**Issue by bartleph** [peterkvt80/vbit2#24]
Hi Peter. Great article and software. Thank you for sharing. I am hoping to use my own page server with this. I have a Subversion server on my local network with modified pages set up. Is it just a case of changing the destination in the getvbit2 file to point to the new repo?
Thanks.

**Comment by ZXGuesser** [comment]
That would work, or you could write your own simpler install script (that doesn't download the unneeded pages.zip for example).
The page directory is specified in the `--dir` argument when vbit2 is started. If you already have vbit2 installed through getvbit2.sh, the page directory is set in the `vb2` script by the `PAGESDIRECTORY` variable.

**Comment by bartleph** [comment]
Many thanks for that. I've managed to get it running to my own Subversion server.
Kind Regards.

**Comment by MICR-OSOFT** [comment]
I find this interesting, But could I get a step-by-step guide on a fresh install of vbit2?

**Comment by peterkvt80** [comment]
This is off topic and covered by the Wiki, but these two videos are great guides. Detailed technical look with a few peeks under the hood. NiksCave [teletext install](https://www.youtube.com/watch?v=PQLhmKh1qI4)
Shorter and entertaining guide for absolute beginners. Tomodachisim534 [teletext install](https://youtu.be/t8CNr6-9620)
