### ISSUE TITLE
vbit-config doesn't work after update

### ISSUE THREAD

**Issue by deveon95** [peterkvt80/vbit2#28]
The new config script depends on the dialog package. This is installed when doing a fresh install, but not when running the update script.

Additionally, these commands are not run when updating, only when doing a new install.
systemctl --user link $HOME/vbit2/teletext-update.timer
systemctl --user link $HOME/vbit2/teletext-update.service

**Comment by ZXGuesser** [comment]
You need to run the postupdate.sh script manually when updating from an older version which cleans up the old scripts and runs the install script to get all the dependencies in order (or just run update again).
Future updates will run any post update actions automatically.
